Problem: still can't deploy
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mkdocs-material 9.5.27+insiders.4.53.11 requires mkdocs~=1.6, but you have mkdocs 1.4.2 which is incompatible.
mkdocs-material 9.5.27+insiders.4.53.11 requires mkdocs-material-extensions~=1.3, but you have mkdocs-material-extensions 1.1.1 which is incompatible.
mkdocs-material 9.5.27+insiders.4.53.11 requires pygments~=2.16, but you have pygments 2.14.0 which is incompatible.
mkdocs-material 9.5.27+insiders.4.53.11 requires
pymdown-extensions~=10.2, but you have pymdown-extensions 9.10 which is
incompatible.
```

Solution: upgrade dependencies for the latest mkdocs